### ISSUE TITLE
API endpoint ​/​streams/​id/​detectFields returns 404

### ISSUE THREAD

**Issue by sergejmueller** [streamr-dev/engine-and-editor#921]
**Current result**
The API call to the `/​streams/​id/​detectFields` endpoint will return a 404 status code, e.g. https://streamr.network/api/v1/streams/y2Vcw0LCR2yW_PukskIH4Q/detectFields

`y2Vcw0LCR2yW_PukskIH4Q` is a [valid stream](https://streamr.network/api/v1/streams/y2Vcw0LCR2yW_PukskIH4Q).

The `Autodetect fields` feature at Streamr Core is affected too.

**Expected result**
The API call returns a valid 200 status response with detected stream fields.

<img width="942" alt="Bildschirmfoto 2021-02-11 um 18 19 21" src="https://user-images.githubusercontent.com/108992/107673045-e0a88700-6c95-11eb-9298-fffc5b9a3e6b.png">
<img width="470" alt="Bildschirmfoto 2021-02-11 um 18 11 40" src="https://user-images.githubusercontent.com/108992/107673057-e56d3b00-6c95-11eb-95ea-0c3e9c34c9de.png">

**Comment by tumppi** [comment]
Hi Sergej and thank you for reporting this issue!

We are currently working on v5.0 release of `streamr-client-javascript` which will contain this functionality. As we are moving towards decentralization it's becoming increasingly difficult to maintain server-side features that do authenticated calls on behalf of clients, like manipulate stream metadata. That's why we are relocating the feature away from the backend.

Streamr Core will be fixed in the upcoming weeks to use this new and shiny feature from `streamr-client-javascript` once it's published.

**Comment by sergejmueller** [comment]
Thanks, @tumppi 
I close the issue. If you want, you can create a follow-up issue.
