### ISSUE TITLE
Some streams with empty content

### ISSUE THREAD

**Issue by sergejmueller** [streamr-dev/engine-and-editor#922]
**Current result**
There are currently over 100 streams that return an empty content when called the `/data/partitions/0/last` endpoint. E.g:
* https://streamr.network/api/v1/streams/4mAnhvybRBC2MGH9ffo5qQ/data/partitions/0/last
* https://streamr.network/api/v1/streams/N18yeBSrR8-NKWDNf4p2_w/data/partitions/0/last

All of them are valid streams.

Some streams do not deliver any content at the first endpoint call. The stream data is returned when the request is repeated again and again. Another streams never get content.

**Expected result**
All streams should return data content.

**Comment by sergejmueller** [comment]
See the `ISFREEANDEMPTY` value/number on [streams key facts](https://streamr.network/marketplace/products/02ccb4193a0a472dad2bd1d625c010a7f4e60c3955694a5e9d4d8f18e274064e/streamPreview/0x688759bcbb6adf32a07e91f6de84d181b252e655%2Fstreamr%2Fgrowth%2Fstreams)

**Comment by fonty1** [comment]
Hey @sergejmueller, thanks for the thought provoking ticket!

We checked through Cassandra and no rows existed for these streams. But this isn't necessarily a technical fault since streams will respect the parameter `storageDays` that indicates how many days data will be stored for before being wiped. So valid streams can exist without having any immediate data to resend.

The most likely underlying problem here is that the stream owners have abandoned their stream at some point. Usually there is an integration script that needs to be run to publish the data from the source to the stream. We're working on culling those neglected streams from the Marketplace but it will take some time.

**Comment by sergejmueller** [comment]
Thanks, @fonty1 
I close the issue. If you want, you can create a follow-up issue.
